const canvas = document.querySelector('canvas')
const ctx = canvas.getContext('2d')
canvas.width = innerWidth
canvas.height = innerHeight

const VERSION = "0.3.1"
const CORNERLABEL = "MarioJS " + VERSION
const BLOCKSIZE = 32
const BLOCKCOLS = 24//*32
const BLOCKROWS = 18//*24
const BW = BLOCKSIZE*BLOCKCOLS//500 //bound width
const BH = BLOCKSIZE*BLOCKROWS//800 //bound height
const BTHICK = 20 //thickness
const BX = (canvas.width-BW)/2-BTHICK
const BY = BTHICK*2
const SCROLLTHICK = BLOCKSIZE*6
const SPEED = 5//4
const GRAVITY = 0.5
const ACCELERATION = 0.2

const ASSETPATH = "./assets/"
const music = new Audio(ASSETPATH+"ssbb-waluigi.ogg")
const audiojump = new Audio(ASSETPATH+"player-jump.ogg")
const audiodied = new Audio(ASSETPATH+"player-died.ogg")
const spriteblock = new Image()
spriteblock.src = ASSETPATH+"block.png"
const spriteground = new Image()
spriteground.src = ASSETPATH+"block-1.png"
const spritelava = new Image()
spritelava.src = ASSETPATH+"block-2.png"
const spritebridge = new Image()
spritebridge.src = ASSETPATH+"bridge.png"
const spritemario = new Image()
spritemario.src = ASSETPATH+"mario-2.png"
const spritebg1 = new Image()
spritebg1.src = ASSETPATH+"bg-1.png"
const spritebg2 = new Image()
spritebg2.src = ASSETPATH+"bg-2.png"

const font = new Image()
font.src = ASSETPATH+"font.png"